"""Project-level artifacts: tailoring profile, charter, scope structure, stakeholders."""

import re
from datetime import date, datetime
from typing import Literal
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError

from pydantic import Field, field_validator, model_validator

from pm_agent.schemas.common import Artifact, Engagement, Model

_REPO_RE = re.compile(r"^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$")
_PROJECT_RE = re.compile(r"^[A-Za-z0-9_.-]+/\d+$")
_EMAIL_RE = re.compile(r"^[^@\s,;<>]+@[^@\s,;<>]+\.[^@\s,;<>]+$")
_TIME_RE = re.compile(r"^([01]\d|2[0-3]):[0-5]\d$")
WEEKDAYS = ("mon", "tue", "wed", "thu", "fri", "sat", "sun")

DEFAULT_PLAYBOOKS = [
    "pmbok8.governance.initiate_project",
    "pmbok8.scope.develop_scope_structure",
    "pmbok8.schedule.develop_schedule",
    "pmbok8.risk.identify_and_analyze_risks",
    "pmbok8.governance.monitor_and_control_performance",
    "pmbok8.stakeholders.manage_communications",
    "pmbok8.governance.assess_and_implement_changes",
]


class RagThresholds(Model):
    """Variance thresholds that turn metrics into RAG status.

    Status colours are computed from these numbers, never generated by the model,
    and only a human may change them (see governance.rules).
    """

    spi_green: float = Field(0.95, description="SPI at or above this is green.")
    spi_amber: float = Field(0.85, description="SPI at or above this (but below green) is amber.")
    aging_wip_amber: int = Field(1, description="Items older than the cycle-time P85 that make it amber.")
    aging_wip_red: int = 3
    blocked_amber: int = 1
    blocked_red: int = 3
    risk_score_amber: int = Field(10, description="An open risk with probability x impact at or above this is amber.")
    risk_score_red: int = 15
    scope_growth_amber: float = Field(
        0.10, description="Net growth of the release scope since the baseline (0.10 = 10%).")
    scope_growth_red: float = 0.20

    @model_validator(mode="after")
    def _ordered(self) -> "RagThresholds":
        if self.spi_amber > self.spi_green:
            raise ValueError("spi_amber must not exceed spi_green")
        for low, high in [("aging_wip_amber", "aging_wip_red"), ("blocked_amber", "blocked_red"),
                          ("risk_score_amber", "risk_score_red"), ("scope_growth_amber", "scope_growth_red")]:
            if getattr(self, low) > getattr(self, high):
                raise ValueError(f"{low} must not exceed {high}")
        return self


class StatusMapping(Model):
    """How GitHub labels map onto work-item states, types and estimates."""

    in_progress_labels: list[str] = Field(default_factory=lambda: ["in progress", "in-progress", "doing", "wip"])
    blocked_labels: list[str] = Field(default_factory=lambda: ["blocked"])
    epic_labels: list[str] = Field(default_factory=lambda: ["epic"])
    bug_labels: list[str] = Field(default_factory=lambda: ["bug"])
    estimate_label_prefixes: list[str] = Field(
        default_factory=lambda: ["points:", "sp:", "estimate:"],
        description="A label such as 'points:3' sets the item's estimate to 3.",
    )
    project_status_field: str = Field("Status", description="Single-select field read from the GitHub project.")
    project_status_states: dict[str, Literal["todo", "in_progress", "blocked", "done"]] = Field(
        default_factory=lambda: {
            "todo": "todo", "backlog": "todo", "ready": "todo", "new": "todo",
            "in progress": "in_progress", "in review": "in_progress", "doing": "in_progress",
            "blocked": "blocked", "done": "done",
        },
        description="Project status option (case-insensitive) -> work-item state. Unlisted options are ignored.",
    )


class Schedule(Model):
    """When a playbook runs unattended. Only a human may add or change schedules."""

    playbook: str = Field(description="Playbook prompt name, e.g. 'monitor_and_control_performance'.")
    cadence: Literal["daily", "weekdays", "weekly"]
    day: Literal["mon", "tue", "wed", "thu", "fri", "sat", "sun"] | None = Field(
        None, description="Required for weekly schedules.")
    time: str = Field("08:00", description="Local time, HH:MM, in the profile's timezone.")
    enabled: bool = True

    @field_validator("time")
    @classmethod
    def _time_format(cls, value: str) -> str:
        if not _TIME_RE.match(value):
            raise ValueError(f"time must be HH:MM (24h), got {value!r}")
        return value

    @model_validator(mode="after")
    def _weekly_needs_day(self) -> "Schedule":
        if (self.cadence == "weekly") != (self.day is not None):
            raise ValueError("weekly schedules need a day, and only weekly schedules take one")
        return self


class ProjectProfile(Artifact):
    """Tailoring profile (PMBOK 8 Tailoring section). Its id equals the project id."""

    kind = "project_profile"

    name: str
    approach: Literal["adaptive", "predictive", "hybrid"] = "adaptive"
    repos: list[str] = Field(default_factory=list, description="GitHub repositories as 'owner/name'.")
    iteration_days: int = Field(14, ge=1, le=90)
    start_date: date | None = None
    target_date: date | None = None
    release_milestone: str | None = Field(
        None, description="GitHub milestone whose issues form the release scope used for forecasting."
    )
    complexity: Literal["low", "medium", "high"] = "medium"
    active_playbooks: list[str] = Field(default_factory=lambda: list(DEFAULT_PLAYBOOKS))
    thresholds: RagThresholds = Field(default_factory=RagThresholds)
    status_mapping: StatusMapping = Field(default_factory=StatusMapping)
    github_project: str | None = Field(
        None, description="GitHub project (v2) whose Status field drives work-item state, as 'owner/number'.")
    timezone: str = Field("UTC", description="IANA timezone for schedules, e.g. 'Asia/Kolkata'.")
    schedules: list[Schedule] = Field(default_factory=list)
    report_recipients: list[str] = Field(
        default_factory=list, description="Who status-report email drafts are addressed to.")
    calendar_query: str | None = Field(
        None, description="Only calendar events matching this text are visible to the copilot.")

    @field_validator("repos")
    @classmethod
    def _repo_format(cls, repos: list[str]) -> list[str]:
        for repo in repos:
            if not _REPO_RE.match(repo):
                raise ValueError(f"repo must look like 'owner/name', got {repo!r}")
        return repos

    @field_validator("github_project")
    @classmethod
    def _project_format(cls, value: str | None) -> str | None:
        if value is not None and not _PROJECT_RE.match(value):
            raise ValueError(f"github_project must look like 'owner/number', got {value!r}")
        return value

    @field_validator("timezone")
    @classmethod
    def _known_timezone(cls, value: str) -> str:
        try:
            ZoneInfo(value)
        except (ZoneInfoNotFoundError, ValueError):
            raise ValueError(f"unknown timezone {value!r}") from None
        return value

    @field_validator("report_recipients")
    @classmethod
    def _emails(cls, values: list[str]) -> list[str]:
        for value in values:
            if not _EMAIL_RE.match(value):
                raise ValueError(f"not an email address: {value!r}")
        return values

    @model_validator(mode="after")
    def _id_is_project(self) -> "ProjectProfile":
        if self.id != self.project_id:
            raise ValueError("a project profile's id must equal its project_id")
        if self.start_date and self.target_date and self.target_date < self.start_date:
            raise ValueError("target_date must not be before start_date")
        return self


class Objective(Model):
    id: str
    statement: str
    success_criteria: list[str] = Field(min_length=1)


class Milestone(Model):
    name: str
    target_date: date | None = None


class Charter(Artifact):
    """Output of 'Initiate Project or Phase'. Only a human can approve it."""

    kind = "charter"

    title: str
    purpose: str
    objectives: list[Objective] = Field(min_length=1)
    in_scope: list[str] = Field(min_length=1)
    out_of_scope: list[str] = Field(default_factory=list)
    milestones: list[Milestone] = Field(default_factory=list)
    budget: float | None = Field(None, ge=0)
    assumptions: list[str] = Field(default_factory=list)
    constraints: list[str] = Field(default_factory=list)
    key_risks: list[str] = Field(default_factory=list)
    sponsor: str | None = None
    pm_authority: str | None = None
    sustainability: list[str] = Field(
        default_factory=list,
        description="Environmental, social and economic considerations (PMBOK 8 sustainability principle).",
    )
    approved_by: str | None = None
    approved_at: datetime | None = None

    @model_validator(mode="after")
    def _unique_objectives(self) -> "Charter":
        ids = [o.id for o in self.objectives]
        if len(ids) != len(set(ids)):
            raise ValueError("objective ids must be unique")
        return self


class ScopeElement(Model):
    id: str
    title: str
    element_type: Literal["epic", "story"] = "story"
    parent: str | None = Field(None, description="Id of the parent epic, for stories.")
    objective_ids: list[str] = Field(default_factory=list, description="Charter objectives this element serves.")
    work_item_id: str | None = Field(None, description="Matching GitHub issue, e.g. 'owner/repo#12'.")
    acceptance_criteria: list[str] = Field(default_factory=list)


class ScopeStructure(Artifact):
    """Output of 'Develop Scope Structure': for agile work, an epic/story map."""

    kind = "scope_structure"

    elements: list[ScopeElement] = Field(default_factory=list)

    @model_validator(mode="after")
    def _consistent(self) -> "ScopeStructure":
        ids = [e.id for e in self.elements]
        if len(ids) != len(set(ids)):
            raise ValueError("scope element ids must be unique")
        known = set(ids)
        for element in self.elements:
            if element.parent is not None and element.parent not in known:
                raise ValueError(f"element {element.id} has unknown parent {element.parent}")
        return self


class Stakeholder(Artifact):
    kind = "stakeholder"
    id_prefix = "S"

    name: str
    role: str
    interest: int = Field(ge=1, le=5)
    influence: int = Field(ge=1, le=5)
    current_engagement: Engagement = "neutral"
    desired_engagement: Engagement = "supportive"
    communication: str | None = Field(None, description="Preferred channel and frequency.")
    notes: str | None = None
